### PR TITLE
Introduces the ARG in Dockerfile  

### PR DESCRIPTION
**Pull request by yashsingh74**
The PR introduces the ARG in the Dockerfile which will help to updated the values like images using the `--build-arg` without updating the Dockerfile.

### CODE REVIEW

**Comment by Tantalor93** [comment]
> The PR introduces the ARG in the Dockerfile which will help to updated the values like images using the --build-arg without updating the Dockerfile.

hello, thanks for the PR, but sadly the reasoning is not cleat to me, what issue does it solve, or what is the benefit?

**Comment by yashsingh74** [comment]
@Tantalor93 
I reason the introduced this change is because there are some cases where I want to build the coredns not from scratch or  from different BASE_IMAGE. Now with the --build-args parameter I don't need to change the Dockerfile and hardcoding the values instead I can build the images using the CLI by passing the `--build-args` parameters like [here](https://docs.docker.com/engine/reference/commandline/build/#build-arg). This will also helps to keep the code clean without manually overwriting the values.

**Comment by mariuskimmina** [comment]
Thanks for the PR @yashsingh74 . 
@Tantalor93  it sounds reasonable to me, e.g. when you want to spin up a CoreDNS container to test certain things and you want to get a shell in the container, from scratch gives you basically nothing and in such a case quickly building a CoreDNS image with a different base could be nice.

**Comment by ivyostosh** [comment]
Any update on when this PR can be merged?

**Comment by SuperQ** [comment]
This needs a rebase.

**Review by SuperQ — APPROVED** [review]
Thanks!

**Comment by ivyostosh** [comment]
I wonder if the failing CI job just needs a re-run?

**Comment by yashsingh74** [comment]
@SuperQ can you help in merging this PR.

**Review by Tantalor93 — APPROVED** [review]
LGTM, thx!

**Review by Tantalor93 — APPROVED** [review]
LGTM, thx!

**Pull request merged**
