### PR TITLE
Update handler.go

### PR DESCRIPTION
**Pull request by lixin963**
tweaks->tweak

### CODE REVIEW

**Comment by chrisohaver** [comment]
Please sign commits with [DCO](https://github.com/coredns/coredns/pull/5453/checks?check_run_id=7015901078).

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Please sign the commits.

**Comment by lixin963** [comment]
Signed-off-by: lixin963 <lixin18@inspur.com>

**Comment by chrisohaver** [comment]
Please sign the commits by following instructions in https://github.com/coredns/coredns/pull/5453/checks?check_run_id=7034127721

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Please sign the commits by following instructions in https://github.com/coredns/coredns/pull/5453/checks?check_run_id=7034127721

**Pull request closed without merging**
