### PR TITLE
Bump golang to 1.20

### PR DESCRIPTION
**Pull request by bitoku**
### 1. Why is this pull request needed and what does it do?

Since the golang 1.20 was released and some of the dependencies are dependent on golang 1.20.

At least I couldn't compile coreDNS with golang:1.18.0.

```
❯ go list -m -json all | jq .GoVersion | sort | uniq                                                          
"1.11"
"1.12"
"1.13"
"1.14"
"1.15"
"1.16"
"1.17"
"1.18"
"1.19"
"1.20"
"1.5"
"1.9"
null
```

### 2. Which issues (if any) are related?

https://github.com/coredns/coredns/pull/5564

### 3. Which documentation changes (if any) need to be made?

No

### 4. Does this introduce a backward incompatible change or deprecation?

No

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
Thanks!

**Comment by SuperQ** [comment]
This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

**Review by chrisohaver — APPROVED** [review]

**Comment by chrisohaver** [comment]
Thanks!

IMO a module min go version check should be part of CI. I'd be kind of surprised if there wasn't a GitHub action out there that checks the module min version vs dependency min versions.

**Comment by bitoku** [comment]
Since I just can't avoid the error in the code coverage CI, I will close this PR.

https://github.com/coredns/coredns/actions/runs/4863731481/jobs/8673299481

```
# github.com/coredns/coredns/plugin/auto [github.com/coredns/coredns/plugin/auto.test]
Error: auto/xfr.go:31:2: syntax error: unexpected var after top level declaration
```
This error can be avoided by adding EOL. (see https://github.com/golang/go/issues/58370)

```
error generating coverage report: write tmp: file already closed
FAIL	github.com/coredns/coredns/plugin/file/tree	0.017s
```
This error, however, can't be avoided. It is reproducible in local as well

```
❯ go version                                                                                 
go version go1.20.3 darwin/amd64

❯ go test -covermode=atomic -race ./...; [ -f cover.out ] && cat cover.out >> ../coverage.txt
error generating coverage report: write tmp: file already closed
FAIL    github.com/coredns/coredns/plugin/file/tree     0.457s
FAIL
```

**Pull request closed without merging**
