### PR TITLE
update all +build statements

### PR DESCRIPTION
**Pull request by mqasimsarfraz**
Signed-off-by: MQasimSarfraz <syed.qasim.sarfraz@gmail.com>

### 1. Why is this pull request needed and what does it do?
As per [go 1.17](https://go.dev/doc/go1.17), "The go command now understands //go:build lines and prefers them over // +build lines". This PR includes changes after `gofmt` to add new pragmas. The changes are backward compatible and `+build` should be removed in future once needed.

### CODE REVIEW

**Comment by chrisohaver** [comment]
I'm thinking we can remove the older style now, since we already require at least go 1.17.

**Comment by mqasimsarfraz** [comment]
@chrisohaver I also think we should be fine removing old style. Especially since it will be removed with go 1.18. So if it makes sense I go ahead the clean them in the same PR?

**Comment by chrisohaver** [comment]
> @chrisohaver I also think we should be fine removing old style. Especially since it will be removed with go 1.18. So if it makes sense I go ahead the clean them in the same PR?

Yes.

**Comment by mqasimsarfraz** [comment]
@chrisohaver Can you please have a look again?

**Review by yongtang — APPROVED** [review]

**Pull request merged**
