### PR TITLE
plugin/file: fix a wildcard lookup bug in multi-label condition

### PR DESCRIPTION
**Pull request by victory460**
Signed-off-by: xuweiwei <xuweiwei_yewu@cmss.chinamobile.com>

### 1. Why is this pull request needed and what does it do?

In a complex scenario, the wildcard lookup work not correctly.

Corefile:

```
example.org:1053 {
    file db.example.org example.org
    log
    debug
}
```

db.example.org:

```
$ORIGIN example.org.
@	3600 IN	SOA sns.dns.icann.org. noc.dns.icann.org. (
				2017042745 ; serial
				7200       ; refresh (2 hours)
				3600       ; retry (1 hour)
				1209600    ; expire (2 weeks)
				3600       ; minimum (1 hour)
				)

	3600 IN NS a.iana-servers.net.
	3600 IN NS b.iana-servers.net.


*  IN  A  10.1.1.1
server1  IN  A  10.1.1.2

```

When `dig test.server1.example.org` , it shoud answer `10.1.1.1`. But it answer none record.

```shell
$ dig @127.0.0.1 -p 1053 test.server1.example.org

; <<>> DiG 9.10.6 <<>> @127.0.0.1 -p 1053 test.server1.example.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 37049
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test.server1.example.org.	IN	A

;; AUTHORITY SECTION:
example.org.		3600	IN	SOA	sns.dns.icann.org. noc.dns.icann.org. 2017042745 7200 3600 1209600 3600

;; Query time: 0 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Fri Jan 07 16:14:49 CST 2022
;; MSG SIZE  rcvd: 134
```

### 2. Which issues (if any) are related?
None.
### 3. Which documentation changes (if any) need to be made?
None.
### 4. Does this introduce a backward incompatible change or deprecation?
None.

### CODE REVIEW

**Review by chrisohaver — CHANGES_REQUESTED** [review]
> ```
> *  IN  A  10.1.1.1
> server1  IN  A  10.1.1.2
> ```
> When dig test.server1.example.org , it shoud answer 10.1.1.1. But it answer none record.

This is not the correct expectation. The `server1` record prevents wildcard record synthesization "below it".  NXDOMAIN is the correct answer.

From RFC 1034 ...

> Wildcard RRs do not apply:
> [...]
>   - When the query name or a name between the wildcard domain and
     the query name is know to exist.  For example, if a wildcard
     RR has an owner name of "*.X", and the zone also contains RRs
     attached to B.X, the wildcards would apply to queries for name
     Z.X (presuming there is no explicit information for Z.X), but
     not to B.X, A.B.X, or X.

**Comment by chrisohaver** [comment]
> NXDOMAIN is the correct answer.

There should be a test added to validate this case; one that would fail with this PR.

**Comment by victory460** [comment]
> > NXDOMAIN is the correct answer.
> 
> There should be a test added to validate this case; one that would fail with this PR.

Thanks, you are right. We add a lookup test case for wildcard RRs do not apply. #5078 
Want to you review it, when you have time.

**Comment by victory460** [comment]
> > ```
> > *  IN  A  10.1.1.1
> > server1  IN  A  10.1.1.2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When dig test.server1.example.org , it shoud answer 10.1.1.1. But it answer none record.
> 
> This is not the correct expectation. The `server1` record prevents wildcard record synthesization "below it". NXDOMAIN is the correct answer.
> 
> From RFC 1034 ...
> 
> > Wildcard RRs do not apply:
> > [...]
> > 
> > * When the query name or a name between the wildcard domain and
> >   the query name is know to exist.  For example, if a wildcard
> >   RR has an owner name of "*.X", and the zone also contains RRs
> >   attached to B.X, the wildcards would apply to queries for name
> >   Z.X (presuming there is no explicit information for Z.X), but
> >   not to B.X, A.B.X, or X.

Thanks, you are right. I have a question that if db.example.org is :
```
$ORIGIN example.org.
@	3600 IN	SOA sns.dns.icann.org. noc.dns.icann.org. (
				2017042745 ; serial
				7200       ; refresh (2 hours)
				3600       ; retry (1 hour)
				1209600    ; expire (2 weeks)
				3600       ; minimum (1 hour)
				)

	3600 IN NS a.iana-servers.net.
	3600 IN NS b.iana-servers.net.


*  IN  A  10.1.1.1
b.c  IN  A  10.1.1.2
```
When `dig a.b.c.example.org` , what the correct expectation? NXDOMAIN ? @chrisohaver

**Comment by chrisohaver** [comment]
> ```
> *  IN  A  10.1.1.1
> b.c  IN  A  10.1.1.2
> ```
> 
> 
>     
>   
> 
> When `dig a.b.c.example.org` , what the correct expectation? NXDOMAIN ?

Yes.

**Comment by victory460** [comment]
> > ```
> > *  IN  A  10.1.1.1
> > b.c  IN  A  10.1.1.2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When `dig a.b.c.example.org` , what the correct expectation? NXDOMAIN ?
> 
> Yes.

Thanks. But now it answer 10.1.1.1,  we will try to fix it later.

**Comment by chrisohaver** [comment]
> Thanks. But now it answer 10.1.1.1, we will try to fix it later

See #4655

**Pull request closed without merging**
