### PR TITLE
sub domains ->subdomains

### PR DESCRIPTION
**Pull request by lixin963**
I think there is something wrong here

### CODE REVIEW

**Comment by mariuskimmina** [comment]
Please sign the DCO (https://github.com/apps/dco)

Ah, I just saw you did sign the last commit - all commits need to be signed tho.It would probably be best to rebase and have a single, signed commit.

**Comment by chrisohaver** [comment]
Please sign the commits by following instructions in https://github.com/coredns/coredns/pull/5464/checks?check_run_id=7068514633

e.g. `git rebase HEAD~3 --signoff`

**Review by lixin963 — COMMENTED** [review]
Signed-off-by: lixin18 [68135097+lixin963@users.noreply.github.com]

**Review by lixin963 — COMMENTED** [review]
Signed-off-by: lixin18 [68135097+lixin963@users.noreply.github.com]

**Comment by chrisohaver** [comment]
> Signed-off-by: lixin18 [[68135097+lixin963@users.noreply.github.com](mailto:68135097+lixin963@users.noreply.github.com)]

It doesn’t work like that. You’ve got to sign the commits with git per the instructions given to you.  Writing the sign off message in a GitHub comment isn’t the same thing.

**Review by chrisohaver — CHANGES_REQUESTED** [review]
https://github.com/coredns/coredns/pull/5464#issuecomment-1168118464

**Pull request closed without merging**
