### PR TITLE
plugin/secondary: Retry initial transfer until successful

### LINKED ISSUE #4661: plugin/secondary: Retries on i/o-timeout on startup
Is there a way to configure the `secondary`-plugin to do automatic retries if it fails to load a zone-file?
Or is there some way that I can trigger a reload on zones that failed?

I'm currently setting up a CoreDNS server with secondary, to handle primary DNS outages, but I sometimes get data like this:

```plain
CoreDNS-1.8.4
linux/amd64, go1.16.4, 053c4d5
[INFO] plugin/file: Transferred: <host1>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host2>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host3>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host4>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host5>. from <axfr-host>:53
[INFO] plugin/file: Transferred: <host6>. from <axfr-host>:53
[ERROR] plugin/file: Failed to transfer `<host7>.' from "<axfr-host>:53": read tcp <local-ip>:33580-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host8>.' from "<axfr-host>:53": read tcp <local-ip>:33602-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host9>.' from "<axfr-host>:53": read tcp <local-ip>:33596-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host10>.' from "<axfr-host>:53": read tcp <local-ip>:33598-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host11>.' from "<axfr-host>:53": read tcp <local-ip>:33590-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host12>.' from "<axfr-host>:53": read tcp <local-ip>:33610-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host13>.' from "<axfr-host>:53": read tcp <local-ip>:33586-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host14>.' from "<axfr-host>:53": read tcp <local-ip>:33608-><axfr-host>:53: i/o timeout
[ERROR] plugin/file: Failed to transfer `<host15>.' from "<axfr-host>:53": read tcp <local-ip>:33582-><axfr-host>:53: i/o timeout
[INFO] plugin/file: Transferred: <host16>. from <axfr-host>:53
```

The DNS provider is DNSimple.

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. Why is this pull request needed and what does it do?

Retries initial transfer attempt if failed.

### 2. Which issues (if any) are related?

fixes #4661

### CODE REVIEW

**Comment by miekg** [comment]
Ideally this would need a test, hence I didn't propose my patch as a pr
yet.

We just need a non responsive master that works after a short while. This
would imply the sleep needs to be configurable.

**Comment by miekg** [comment]
Fine if you add/make those changes?

**Comment by chrisohaver** [comment]
Apologies, I didn't intend to take your code as mine.  I had already started on this, and then saw your suggested code afterwards - at which point I adjusted the log message and sleep amount to match your suggestion. In retrospect, that looks like I just copy pasted your patch as mine.

**Comment by miekg** [comment]
Haha LOL. Goes to show how good Go is. Two folks coming up with an
identical solution.

But tests :)

**Comment by chrisohaver** [comment]
Using a backoff sleep speeds up the test, without introducing a plugin option.

**Comment by chrisohaver** [comment]
> But tests :)

Re-opened with tests added.

**Review by miekg — APPROVED** [review]
this warrant some doc updates. I'll send a PR for that separately

**Comment by miekg** [comment]
see https://github.com/coredns/coredns/pull/4686

**Pull request merged**
