### PR TITLE
Steering Committee Membership: johnbelamaric

### PR DESCRIPTION
**Pull request by johnbelamaric**
I would like to extend my steering membership for another year.

Thank you.

### CODE REVIEW

**Comment by johnbelamaric** [comment]
https://github.com/coredns/coredns/issues/6327

**Review by bradbeam — APPROVED** [review]

**Review by SuperQ — APPROVED** [review]
:+1:

**Comment by chrisohaver** [comment]
+1

**Review by greenpau — APPROVED** [review]

**Review by Isolus — APPROVED** [review]

**Comment by stp-ip** [comment]
+1

**Review by jameshartig — APPROVED** [review]

**Review by Tantalor93 — APPROVED** [review]

**Pull request merged**
