### PR TITLE
feat: add docker source label

### PR DESCRIPTION
**Pull request by viceice**
### 1. Why is this pull request needed and what does it do?
This allows [renovate](/renovatebot/renovate) to link to source repo and fetch changelogs (if available)

### 2. Which issues (if any) are related?
not checked

### 4. Does this introduce a backward incompatible change or deprecation?
no

### CODE REVIEW

**Comment by yongtang** [comment]
@viceice Is this label a standard used in similar projects like Kubernetes/etc?

**Comment by viceice** [comment]
Yes, official opencontainers label.

https://www.github.com/opencontainers/image-spec/tree/master/annotations.md

**Comment by miekg** [comment]
there are many more labels, just adding a link to the repo doesn't seem like it adds much. From memory git hash and other fluff like it can also be added.

I don't think this adds much, and if you need it you can easily build your own pipeline and add labels

**Comment by viceice** [comment]
I know, do you like me to add more labels?

We use it at renovate, reading it from the registry to find the source of the image. That way renovate can fetch release note from source repo to show in it's update pr's.

We also use it to link to the source from the pr.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] feat: add doc..." ]
>I know, do you like me to add more labels?
>
>We use it at renovate, reading it from the registry to find the source of the
>image. That way renovate can fetch release note from source repo to show in
>it's update pr's.
>
>We also use it to link to the source from the pr.

no, I don't think we should add any labels. The whole process you descibe seems to come
down to not having to google to view the changelog.

**Comment by yongtang** [comment]
@viceice Honestly I would prefer not to add a specific label unless the label is used by a majority or a significant portion of the users. You can always build your own docker image with pre-built CoreDNS static binary. The effort is with very minimal.

**Comment by viceice** [comment]
Ok, no problem.

**Comment by viceice** [comment]
Our hope was to add those label to more images, so it will be adopted by more and more images over time.

**Pull request closed without merging**
