### PR TITLE
Fix pinning of github actions

### PR DESCRIPTION
**Pull request by yongtang**
It is recommended to pin github actions with hash so that an action is not posing an unknown security risk (as the actions itself is not written by us).

Note while pinning to commit ID may looks to be tedious, they will be automatically updated by dependabot. So there is no additional burden.

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by chrisohaver — COMMENTED** [review]
> they will be automatically updated by dependabot

Will they be updated to use the latest tag or commit hash? i.e. will dependabot undo the pinning?

**Comment by chrisohaver** [comment]
> It is recommended to pin github actions with hash so that an action is not posing an unknown security risk (as the actions itself is not written by us).

I presume the risk here is that a bad actor could delete and recreate a tag such that it points to a different commit that contains malicious code.

**Comment by yongtang** [comment]
@chrisohaver  The pinning will not be undone, see example: https://github.com/yongtang/coredns/pull/8

**Review by chrisohaver — APPROVED** [review]
LGTM.  I did not verify any of the commit hash values.

**Comment by yongtang** [comment]
> I presume the risk here is that a bad actor could delete and recreate a tag such that it points to a different commit that contains malicious code.

@chrisohaver the integrity of the actions can be changed if only version is specified The github actions we use are from open source community. While we trust the community, it can be possible that some outside hackers hacked into some repos and modify the actions by changing the content referenced by versions. Hash at least guarantees the integrity of the actions used.

**Comment by chrisohaver** [comment]
> > I presume the risk here is that a bad actor could delete and recreate a tag such that it points to a different commit that contains malicious code.
> 
> @chrisohaver the integrity of the actions can be changed if only version is specified The github actions we use are from open source community. While we trust the community, it can be possible that some outside hackers hacked into some repos and modify the actions by changing the content referenced by versions. Hash at least guarantees the integrity of the actions used.

Sounds like a long winded "yes".

**Pull request merged**
