### PR TITLE
introduce new plugin to prevent DNS cache snooping

### PR DESCRIPTION
**Pull request by Tantalor93**
Signed-off-by: Ondřej Benkovský <ondrej.benkovsky@jamf.com>

Hello 👋 I would like to circulate an idea for a new CoreDNS plugin, I prepared a draft how it could look like and I would welcome comments

### 1. Why is this pull request needed and what does it do?
This PR adds a new plugin that can to some extent prevent [DNS cache snooping attacks](https://kb.isc.org/docs/aa-00509). This is inspired by the existing module in [Knot Resolver](https://knot-resolver.readthedocs.io/en/stable/modules-refuse_nord.html).

### 3. Which documentation changes (if any) need to be made?
mention new plugin in documentation

### 4. Does this introduce a backward incompatible change or deprecation?
no

### CODE REVIEW

**Comment by chrisohaver** [comment]
The readme should make it clear that this intends to prevent cache snooping of _upstream recursive resolvers_, not of the CoreDNS cache.
The CoreDNS cache will send the request to the next plugin regardless of RD bit state, so an attacker cannot deduce whether or not an item is in the cache by setting the RD bit.

**Review by chrisohaver — COMMENTED** [review]
Thanks!  

The readme should make it clear that this intends to prevent cache snooping of upstream recursive resolvers, not of the CoreDNS cache.
The CoreDNS cache will send the request to the next plugin regardless of RD bit state, so an attacker cannot deduce whether or not an item is in the cache by setting the RD bit.  

Thinking out loud - an alternate place to add this feature could be in the _forward_ plugin... since it only really applies when the forward plugin is involved.  I.e. an option in the _forward_ plugin that refuses to forward non RD queries.

**Comment by Tantalor93** [comment]
oh right @chrisohaver, CoreDNS cache is not susceptible to cache snooping. This would only prevent upstream DNS cache snooping, so as you said, it would rather make more sense as an option to the `forward` plugin rather than separate plugin🤔  I'll close this 👍

**Comment by chrisohaver** [comment]
I’m not decided on whether or not this makes more sense as a separate plugin or an extension of another. 

Another plugin that could be extended is the acl plugin, adding ability to make flag based rules, in which case there might be some other use cases.

**Pull request closed without merging**
