### PR TITLE
plugin/transfer: Support CIDR notation for 'to'

### LINKED ISSUE #4690: transfer's to does not allow IPv6 CIDR address
**What happened**:

The documentation contradicts the implementation regarding to the **to** statement in the **transfer module**.

Using

        transfer {
          to 2a0a:e5c0::/29
          to 2a01:4f8:150:7092::2/64
        }

I get the error message

```
plugin/transfer: must specify an IP address: `2a0a:e5c0::/29'
```

**What you expected to happen**:

Support AXFR to hosts coming from 2a0a:e5c0::/29.

**How to reproduce it (as minimally and precisely as possible)**:

See above. 

**Anything else we need to know?**:

The documentation says:

```
to ADDRESS… The hosts transfer will transfer to. Use * to permit transfers to all addresses. ADDRESS must be denoted in CIDR notation (e.g., 127.0.0.1⁄32) or just as plain addresses. to may be specified multiple times.
```

Above is clearly cidr and the intent is to allow AXRFs from the given networks.

**Environment**:

- the version of CoreDNS: k8s.gcr.io/coredns/coredns:v1.8.0
- Corefile: See above
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

### PR DESCRIPTION
**Pull request by chrisohaver**
Signed-off-by: Chris O'Haver <cohaver@infoblox.com>

### 1. Why is this pull request needed and what does it do?

Adds support for allowed IP networks (CIDR). 

### 2. Which issues (if any) are related?

Fixes #4690

### CODE REVIEW

**Comment by miekg** [comment]
is this inline with what acl does?

**Comment by chrisohaver** [comment]
> is this inline with what acl does?

Ah - yeah I should probably make this respond with `REFUSED`, instead of passing to next plugin.

Furthermore ... CIDR filtering can be handled entirely by _acl_ instead... albeit less succinctly.

This config using _acl_ ...

```
  acl {
    allow type AXFR net 10.1.0.0/16
    allow type IXFR net 10.1.0.0/16
    block type AXFR net *
    block type IXFR net *
  }
  transfer {
    to *
  }
```

... would be equivalent to the following config enabled in this PR  ...

```
  transfer {
    to 10.1.0.0/16
  }
```

So strictly speaking this feature isn't needed, unless you see enough value in the shorter config to warrant the functional redundancy.

**Comment by chrisohaver** [comment]
I opened #4711 with doc changes if we don't want to add CIDR restriction directly to `transfer` via this PR.

**Comment by chrisohaver** [comment]
>>is this inline with what acl does?

> Ah - yeah I should probably make this respond with REFUSED, instead of passing to next plugin.

Transfer already does that.  So  yes, the behavior is in-line with how _acl_ does it.

**Comment by chrisohaver** [comment]
Closing since #4711 merged.

**Pull request closed without merging**
