### PR TITLE
core: add log listeners for k8s_event plugin

### PR DESCRIPTION
**Pull request by xh4n3**
### 1. Why is this pull request needed and what does it do?
I proposed a plugin k8s_event earlier in the issue https://github.com/coredns/coredns/issues/5437 .

image

In this pull request, I added the method `LoadInterceptor` to let event adaptors like k8s_event register themselves.

And I pushed a draft version of k8s_event to a personal repository https://github.com/xh4n3/k8s_event .

It may not be the final version, I'd like to hear some feedback first.

If we're all satisfied, maybe I can push the k8s_event to some repository under the CoreDNS organization?

### 2. Which issues (if any) are related?
https://github.com/coredns/coredns/issues/5437

### 3. Which documentation changes (if any) need to be made?
This pr is not facing the end-users, so no doc change.
After this gets merged, I will create another plugin doc page on the coredns.io website.

### 4. Does this introduce a backward incompatible change or deprecation?
No.

### CODE REVIEW

**Comment by chrisohaver** [comment]
Thanks!

It appears that only one plugin can intercept log messages, the last one taking precedence. Can you add support for multiple  log intercepting plugins?

**Comment by chrisohaver** [comment]
I think of this feature as implemented as more of a "mirror", since the message is still being logged by the log package, and also a copy of the log message is being sent to another function.

The name "interceptor" kind of implies that the log message would sent to an alternate function _instead_ of being logged by log.

(IOW: suggesting we rename to `mirror`, or something other than `interceptor`)

Actually: `listener` works better than `mirror`

**Comment by yongtang** [comment]
I will take a detailed look during the weekend but I like the direction this plugin is heading. We can follow up on where to host this plug-in (in coredns org or repo).

**Comment by xh4n3** [comment]
@chrisohaver Nice suggestions, I've pushed a new commit addressing them.

The new diagram would be like this:
image

BTW, here's an example of the reported events.
```bash
$ kubectl get ev -A -w
NAMESPACE   LAST SEEN   TYPE      REASON           OBJECT              MESSAGE
# when CoreDNS started
default     1s          Normal    CoreDNSInfo      namespace/default   plugin/reload: Running configuration SHA512 = 8d4db1d9149964e0cfda9274ea7500bed395a7d518ca3ef1b7df9980908fd447d9eafed6d017cf89f96ac4b406585b68aece7c108a30c5660f69532d1a74948f
# when i tried to dig with a unreachable upstream
default     0s          Warning   CoreDNSError     namespace/default   plugin/errors: 2 www.ab.com. A: read udp 30.225.16.62:57863->114.114.114.118:53: i/o timeout
default     1s          Warning   CoreDNSError     namespace/default   plugin/errors: 2 www.ab.com. A: read udp 30.225.16.62:52029->114.114.114.118:53: i/o timeout
# when i added the proxy plugin
default     1s          Warning   CoreDNSError     namespace/default   plugin/reload: Corefile changed but reload failed: starting with listener file descriptors: Corefile:16 - Error during parsing: Unknown directive 'proxy'
# when i removed proxy plugin
default     1s          Normal    CoreDNSInfo      namespace/default   plugin/reload: Running configuration SHA512 = 8d4db1d9149964e0cfda9274ea7500bed395a7d518ca3ef1b7df9980908fd447d9eafed6d017cf89f96ac4b406585b68aece7c108a30c5660f69532d1a74948f
default     1s          Warning   CoreDNSWarning   namespace/default   plugin/k8s_event: COREDNS_NAMESPACE or COREDNS_POD_NAME is not set in environment variables, reporting events to default namespace
```

**Review by chrisohaver — COMMENTED** [review]
Thanks, looks good.

Thinking about if we need an RWMutex on `listeners`:  I don't _think_ so, since plugins do their setups serially, and I don't think any plugins try to write to the log in a go routine during setup (i.e. concurrently with other plugins setting up). And plugins should only register a listener during setup, before the server starts.

**Comment by chrisohaver** [comment]
> And plugins should only register a listener during setup, before the server starts.

Although, I see in https://github.com/xh4n3/k8s_event/pull/1, that the listener registration is deferred to onStartup, not during plugin setup ... meaning that it could try to register a listener when other plugins are writing to the log.

So perhaps we _should_ add RWMutex to `listeners`.

**Comment by xh4n3** [comment]
@chrisohaver Thanks, the RWMutex has been added.

@yongtang Any comments on this PR? Please let me know, thanks 😃

**Review by chrisohaver — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
