### PR TITLE
plugin/forward: fix descriptions in README.md

### PR DESCRIPTION
**Pull request by cattyhouse**
### 1. Why is this pull request needed and what does it do?
- add `tls://` prefix in the tls example

without `tls://` prefix, forward will actually use udp/tcp port 53, even there is `tls_servername` configured. this is based on actual test.

- fix a typo

`tls-name` -> `tls_servername`

### 2. Which issues (if any) are related?

none

### 3. Which documentation changes (if any) need to be made?

see **1.**
### 4. Does this introduce a backward incompatible change or deprecation?

no

### CODE REVIEW

**Comment by cattyhouse** [comment]
closes #6078

**Comment by Tantalor93** [comment]
thx, that makes sense! can you sign the commits?
```
git commit --amend --signoff
```

**Comment by cattyhouse** [comment]
i did this on github web. not sure how to sign it in this case.

**Comment by Tantalor93** [comment]
I guess you need to do a local checkout, do the signoff and then push it into the same branch

**Comment by cattyhouse** [comment]
sorry, i don't know what i did, it looks like a mess after `git commit --amend --signoff` and `git push --force` to my repo. thus is it closed automatically. 

however anyone who has permission to edit this repo are free to use the patch.

**Comment by chrisohaver** [comment]
> This branch is [1 commit ahead](https://github.com/cattyhouse/coredns/compare/coredns:coredns:master...patch-1), [3646 commits behind](https://github.com/cattyhouse/coredns/compare/patch-1...coredns:coredns:master) coredns:master.

Should resolve If you pull latest changes from coredns master into your branch.

**Pull request closed without merging**
