### PR TITLE
Update to avoid pseudo-random number

### PR DESCRIPTION
**Pull request by yongtang**
This PR update the usage of rand so that non-global seed is used.

Addresses issue TOB-CDNS-7 in https://github.com/trailofbits/publications/blob/master/reviews/CoreDNS.pdf

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Review by chrisohaver — APPROVED** [review]
lgtm thanks!

**Review by chrisohaver — CHANGES_REQUESTED** [review]
The failure in tests seems to be related?

edit: Ah, yes.  I initially thought only the Coverage test was failing, but I see `/test` is also failing in the same place.

**Comment by yongtang** [comment]
@chrisohaver  I will take a look.

**Review by chrisohaver — APPROVED** [review]
LGTM!

**Pull request merged**
