### PR TITLE
Revert "plugin/file: Fix in wrong answers returned when wildcard and concrete records exist (#4599)"

### PR DESCRIPTION
**Pull request by miekg**
reverting as I don't want to release 1.8.4 with this enabled.

This reverts commit fbf3f07f469a99fcbb5985a41c260a3fad26f908.

### CODE REVIEW

**Review by yongtang — APPROVED** [review]
LGTM

**Comment by yongtang** [comment]
LGTM. Though the tests are failing, wondering if this is caused by the commit or it is a GitHub Actions CI issue?

**Comment by chrisohaver** [comment]
github actions are currently degraded ... they are failing to be scheduled, and eventually get cancelled in all PRs.

**Comment by chrisohaver** [comment]
reopens #4290

**Pull request merged**
