### PR TITLE
update project lead and term

### PR DESCRIPTION
**Pull request by chrisohaver**
Signed-off-by: Chris O'Haver <cohaver@infoblox.com>

### 1. Why is this pull request needed and what does it do?

Since @miekg has recently stepped down as project lead, we should kick off the process to elect a new project lead.

I'm nominating myself with this PR.  Any other maintainers who want to throw their hat in the ring should open a similar PR.
Per our [governance doc](https://github.com/coredns/coredns/blob/master/GOVERNANCE.md#changes-in-project-lead), this PR and any other candidate PRs should remain open for 4 weeks, during which the community may cast +1/-1 votes.

### CODE REVIEW

**Review by johnbelamaric — APPROVED** [review]
+1

I second Chris’s nomination. He has been the most active and involved community member for quite a while now. He has deep knowledge and is always helpful and respectful. I cannot imagine a better person to take over!

**Comment by greenpau** [comment]
+1 for @chrisohaver

**Review by greenpau — APPROVED** [review]

**Review by rajansandeep — APPROVED** [review]
+1 for @chrisohaver. He has been the most involved and has a complete understanding of all aspects of the CoreDNS project.

**Review by Tantalor93 — APPROVED** [review]
+1 for chris 👍

**Review by SuperQ — APPROVED** [review]
:100:

**Review by stp-ip — APPROVED** [review]
All for it. Thank you for taking over.

**Comment by yongtang** [comment]
I think Chris has been a great asset to the CoreDNS project and has done a lot especially recently. On another thought, wondering if changing GOVERNANCE.md to align CoreDNS with some other CNCF projects such as Envoy or Prometheus?

Created a PR #5494 to discuss further on GOVERNANCE.md

**Review by dilyevsky — APPROVED** [review]

**Review by bradbeam — APPROVED** [review]

**Review by Isolus — APPROVED** [review]

**Review by zouyee — APPROVED** [review]

**Comment by chrisohaver** [comment]
Closing this, since going forward with no leader is more popular. #5494

**Pull request closed without merging**
