### PR TITLE
Use dockerhub token instead of password

### PR DESCRIPTION
**Pull request by heiko-braun**
### 1. Why is this pull request needed and what does it do?
It's an attempt to fix (or help with) #6661 

### 2. Which issues (if any) are related?
#6661 
#6638

### 3. Which documentation changes (if any) need to be made?
The release process docs would need be changed to mention that a personal access token for dockerhub is needed: https://github.com/docker/login-action?tab=readme-ov-file#docker-hub

### 4. Does this introduce a backward incompatible change or deprecation?
Not that I am aware of

### CODE REVIEW

**Comment by heiko-braun** [comment]
@chrisohaver You would need to create a dockerhub token and update the action secrets accordingly

**Comment by chrisohaver** [comment]
Thank You!  I am not an admin in the coredns dockerhub org,  so I don't have permission to generate a token for it.
Strictly speaking if this fix works this PR is not necessary. All we need to do is find someone who is an admin in coredns dockerhub org and have them generate a token and update the existing secrets.

**Comment by heiko-braun** [comment]
I didn't look into the login-action deeply, but you might be right. Eventually we can keep DOCKERHUB_USERNAME and simply update it. I have updated it to TOKEN, since it's seems to be best practice.

**Comment by johnbelamaric** [comment]
> Thank You! I am not an admin in the coredns dockerhub org, so I don't have permission to generate a token for it. Strictly speaking if this fix works this PR is not necessary. All we need to do is find someone who is an admin in coredns dockerhub org and have them generate a token and update the existing secrets.

Chris, I am an owner of that repo. What do you need? I can also make you an admin and/or owner.

**Comment by chrisohaver** [comment]
@johnbelamaric thanks John! For now, can you generate a token for your account and update the existing dockerhub_password secret to that token (not your password). Hopefully that works!

thanks!

**Pull request closed without merging**
