### PR TITLE
Bump version to 1.8.7

### PR DESCRIPTION
**Pull request by yongtang**
Bump version to 1.8.7, part of issue #4996

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

**Comment by yongtang** [comment]
@miekg  @chrisohaver Unless there is an objection, I think we can release 1.8.7 first? After that we can prepare a 1.9.0 which will consist of the wildcard changes.

**Comment by chrisohaver** [comment]
@yongtang 

We should consider adding the deprecation warning #5030 in a release before removing wildcard feature.

**Comment by yongtang** [comment]
@chrisohaver With PR #5030 merged, we should be ready to go for 1.8.7.

**Review by chrisohaver — APPROVED** [review]

**Comment by yongtang** [comment]
Actually we probably want to carry #5020 as well.

**Comment by yongtang** [comment]
Probably should have merge #5020 first.

**Pull request merged**
